# trigger build
version: 2
debug: true
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: bash scripts/accept-problem.sh
      - run: bash scripts/push-problem.sh
workflows:
  version: 2
  build:
    jobs:
      - build
